### Get a list of stations

//GET http://localhost:8080/api/stations/

## Get station by name sent as param

//GET http://localhost:8080/api/stations/Hanasaari

## Get list of all journeys

GET http://localhost:8080/api/journeys/
